// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnrtzeqsndhqweibljtf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImducnR6ZXFzbmRocXdlaWJsanRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MTE2MzgsImV4cCI6MjA2MDQ4NzYzOH0.xzlNMzQt0tRsu1wQU8EMLe3qkV0ZT8QBC3Pgaf8wxYo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);